# Generated by Django 3.2.10 on 2024-10-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20241002_0753'),
        ('restaurants', '0002_auto_20241002_0840'),
    ]

    operations = [
    ]
